version: '3'
services:
  main:
    build: .
    container_name: arian-table
    command: npx ts-node-dev --poll --prefer-ts true --interval 500 -- ./src/server/server.ts
    depends_on:
      - mysql
    volumes:
      - .:/workdir
    ports:
      - 8000:8000
    networks:
      - arianrod
  mysql:
    image: mysql:5.7.19
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arian_db
      MYSQL_USER: arian
      MYSQL_PASSWORD: arian
      MYSQL_HOST: mysql
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - arian-mysql-store:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - arianrod
networks:
  arianrod:
    driver: bridge
volumes:
  arian-mysql-store:
