version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:16.7
commands:
  preprocess:
    description: 'パッケージのインストールやビルドを行う'
    steps:
      - run: yarn install
      - run: yarn build
jobs:
  build:
    executor: node
    steps:
      - checkout
      - preprocess
      - run: echo "Build done!"
  test:
    executor: node
    steps:
      - checkout
      - preprocess
      - run: yarn test
  deploy:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Image
          command: docker build -t aqla114/arian-battle-table:latest .
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_USER} --password-stdin
      - run:
          name: Push image to registry
          command: docker push aqla114/arian-battle-table

workflows:
  version: 2
  built-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
